In [6]:
from mp_api.client import MPRester
import pandas as pd

In [12]:
display(xrd_df)

,mp_id,formula,composition,crystal_system,symmetry_symbol,volume,density,xray_peaks,xray_intensities
0,mp-1005,FeP,"{'Fe': 1, 'P': 1}",Orthorhombic,Pnma,90.583862,6.366076,"[23.15086164,31.02195798,33.23866128,34.822846...","[4.73131274,17.6544138,71.4334109,21.8151441,1..."
1,mp-1006367,Ce2HfSe5,"{'Ce': 2, 'Hf': 1, 'Se': 5}",Orthorhombic,Pnma,785.754385,7.215011,"[13.59855865,14.68007171,15.5587516,17.2161627...","[9.04260718,3.88889592,14.8704078,0.0717627581..."
2,mp-1001606,LuFeC2,"{'Lu': 1, 'Fe': 1, 'C': 2}",Orthorhombic,Amm2,45.919844,9.215206,"[24.87354653,25.79708699,30.23085522,36.139916...","[39.06976227,9.24752455,24.85129267,100.0,18.6..."
3,mp-1001613,LuGa,"{'Lu': 1, 'Ga': 1}",Orthorhombic,Cmcm,87.819318,9.253483,"[16.89543051,22.68791393,28.22757053,32.128373...","[0.568120675,9.04300155,29.5353313,100.0,39.95..."
4,mp-1008624,YBiPd,"{'Y': 1, 'Bi': 1, 'Pd': 1}",Cubic,F-43m,74.987877,8.952998,"[23.01240126,26.63332165,38.0207848,44.9107308...","[36.27131039,27.19850555,100.0,19.56480595,8.0..."
...,...,...,...,...,...,...,...,...,...
16420,mp-1213830,Ce3W(ClO2)3,"{'Ce': 3, 'W': 1, 'Cl': 3, 'O': 6}",Hexagonal,P6_3/m,408.805926,6.552238,"[10.94822859,19.02128174,19.71983192,21.998023...","[54.0912233,1.50813133,2.77921414,4.13294744,4..."
16421,mp-1191620,PuB4Ru,"{'Pu': 1, 'B': 4, 'Ru': 1}",Orthorhombic,Pbam,244.423386,10.552355,"[15.29269094,16.67763625,21.34936852,25.258563...","[2.17205238,6.61441181,20.8615588,100.0,34.133..."
16422,mp-1209360,Pr5Bi3Br,"{'Pr': 5, 'Bi': 3, 'Br': 1}",Hexagonal,P6_3/mcm,552.581472,8.482577,"[10.53062158,18.29148783,21.1515142,22.5386135...","[3.2436827,2.33769877,0.804064192,8.14582475,1..."
16423,mp-1190710,Sc5(In2Co)2,"{'Sc': 5, 'In': 4, 'Co': 2}",Orthorhombic,Pbam,440.878854,6.040735,"[10.18858728,12.69727266,15.48118582,19.264295...","[1.37660375,0.0427657761,1.92963728,5.23703683..."
16424,mp-316,MnV,"{'Mn': 1, 'V': 1}",Cubic,Pm-3m,23.289978,7.549046,"[31.32280162,44.88667126,55.75338872,65.354163...","[0.43329361,100.0,0.11666426,14.5409878,0.1386..."

In [46]:
xrd_df = pd.read_csv('xrd_dataset_clean.csv')

# Generate a list of the crystal systems in the dataset:
symm_symbols = sorted(set(xrd_df['symmetry_symbol']))

symm_symbols_canonical = [ SpaceGroup(s).symbol for s in symm_symbols ]

In [50]:
from pymatgen.symmetry.groups import SpaceGroup

sg_symbols = []
for n in range(1,231):
    sg = SpaceGroup.from_int_number(n)
    sg_symbols.append(sg.symbol)

In [51]:
len(sg_symbols)

230

In [52]:
print(set(symm_symbols_canonical) - set(sg_symbols))

set()

In [56]:
print(set(sg_symbols) - set(symm_symbols_canonical))

{'P6_4', 'F-43c', 'P4nc', 'I2_12_12_1', 'Pnc2', 'P4_222', 'P23', 'P6_1', 'P222', 'P4cc', 'P4_22_12', 'P4_2bc', 'P3c1', 'F23', 'P-4', 'Pban', 'Pca2_1', 'P432', 'P622', 'F222', 'P-42c', 'I4_1cd', 'P6cc', 'I432', 'P-4b2', 'P6/mcc', 'P3_2', 'P6', 'Fd-3c', 'F4_132', 'P222_1', 'P6_522', 'P4_2/mcm', 'Pba2', 'P31c', 'P6_2', 'P3_121', 'P4_322', 'P4_232', 'F432', 'P6_5', 'Pn-3n', 'P3_1', 'P4_2mc', 'I-4c2', 'Pcc2', 'P4_3'}

In [57]:
from tqdm import tqdm

sg_data = {}
with MPRester() as mpr:

    for symbol in tqdm(sg_symbols):
        docs = mpr.materials.summary.search(
            energy_above_hull=(0, 1.0),
            spacegroup_symbol=symbol,
            fields=['material_id', 'formula_pretty', 'energy_above_hull'],
        )

        if docs:
            sg_data[symbol] = [dict(doc) for doc in docs]

  0%|                                                                                                                                                               | 0/230 [00:00<?, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/14635 [00:00<?, ?it/s]

  0%|▋                                                                                                                                                      | 1/230 [00:08<32:54,  8.62s/it]

Retrieving SummaryDoc documents:   0%|          | 0/8518 [00:00<?, ?it/s]

  1%|█▎                                                                                                                                                     | 2/230 [00:12<22:53,  6.02s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  1%|█▉                                                                                                                                                     | 3/230 [00:14<15:13,  4.02s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  2%|██▋                                                                                                                                                    | 4/230 [00:15<11:22,  3.02s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  2%|███▎                                                                                                                                                   | 5/230 [00:17<09:43,  2.59s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  3%|███▉                                                                                                                                                   | 6/230 [00:19<08:20,  2.24s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  3%|████▌                                                                                                                                                  | 7/230 [00:20<07:33,  2.04s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  3%|█████▎                                                                                                                                                 | 8/230 [00:22<06:50,  1.85s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  4%|█████▉                                                                                                                                                 | 9/230 [00:23<06:26,  1.75s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  4%|██████▌                                                                                                                                               | 10/230 [00:25<06:10,  1.68s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  5%|███████▏                                                                                                                                              | 11/230 [00:26<05:58,  1.64s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  5%|███████▊                                                                                                                                              | 12/230 [00:28<06:10,  1.70s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  6%|████████▍                                                                                                                                             | 13/230 [00:30<05:58,  1.65s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  6%|█████████▏                                                                                                                                            | 14/230 [00:31<05:48,  1.62s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

  7%|█████████▊                                                                                                                                            | 15/230 [00:33<05:42,  1.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/118 [00:00<?, ?it/s]

  7%|██████████▍                                                                                                                                           | 16/230 [00:35<05:39,  1.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/28 [00:00<?, ?it/s]

  7%|███████████                                                                                                                                           | 17/230 [00:36<05:33,  1.57s/it]

Retrieving SummaryDoc documents:   0%|          | 0/144 [00:00<?, ?it/s]

  8%|███████████▋                                                                                                                                          | 18/230 [00:38<05:50,  1.65s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1036 [00:00<?, ?it/s]

  8%|████████████▍                                                                                                                                         | 19/230 [00:41<07:09,  2.03s/it]

Retrieving SummaryDoc documents:   0%|          | 0/240 [00:00<?, ?it/s]

  9%|█████████████                                                                                                                                         | 20/230 [00:42<06:30,  1.86s/it]

Retrieving SummaryDoc documents:   0%|          | 0/102 [00:00<?, ?it/s]

  9%|█████████████▋                                                                                                                                        | 21/230 [00:44<06:21,  1.82s/it]

Retrieving SummaryDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

 10%|██████████████▎                                                                                                                                       | 22/230 [00:46<06:02,  1.74s/it]

Retrieving SummaryDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

 10%|███████████████                                                                                                                                       | 23/230 [00:47<05:47,  1.68s/it]

Retrieving SummaryDoc documents:   0%|          | 0/43 [00:00<?, ?it/s]

 10%|███████████████▋                                                                                                                                      | 24/230 [00:49<05:31,  1.61s/it]

Retrieving SummaryDoc documents:   0%|          | 0/683 [00:00<?, ?it/s]

 11%|████████████████▎                                                                                                                                     | 25/230 [00:51<05:53,  1.72s/it]

Retrieving SummaryDoc documents:   0%|          | 0/389 [00:00<?, ?it/s]

 11%|████████████████▉                                                                                                                                     | 26/230 [00:52<05:33,  1.64s/it]

Retrieving SummaryDoc documents:   0%|          | 0/4 [00:00<?, ?it/s]

 12%|█████████████████▌                                                                                                                                    | 27/230 [00:54<05:28,  1.62s/it]

Retrieving SummaryDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

 12%|██████████████████▎                                                                                                                                   | 28/230 [00:55<05:22,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/383 [00:00<?, ?it/s]

 13%|██████████████████▉                                                                                                                                   | 29/230 [00:57<05:13,  1.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/26 [00:00<?, ?it/s]

 13%|███████████████████▌                                                                                                                                  | 30/230 [00:58<05:32,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/616 [00:00<?, ?it/s]

 13%|████████████████████▏                                                                                                                                 | 31/230 [01:00<05:26,  1.64s/it]

Retrieving SummaryDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

 14%|████████████████████▊                                                                                                                                 | 32/230 [01:02<05:15,  1.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1043 [00:00<?, ?it/s]

 14%|█████████████████████▌                                                                                                                                | 33/230 [01:05<06:36,  2.01s/it]

Retrieving SummaryDoc documents:   0%|          | 0/49 [00:00<?, ?it/s]

 15%|██████████████████████▏                                                                                                                               | 34/230 [01:06<06:28,  1.98s/it]

Retrieving SummaryDoc documents:   0%|          | 0/124 [00:00<?, ?it/s]

 15%|██████████████████████▊                                                                                                                               | 35/230 [01:08<06:00,  1.85s/it]

Retrieving SummaryDoc documents:   0%|          | 0/745 [00:00<?, ?it/s]

 16%|███████████████████████▍                                                                                                                              | 36/230 [01:10<05:44,  1.78s/it]

Retrieving SummaryDoc documents:   0%|          | 0/25 [00:00<?, ?it/s]

 16%|████████████████████████▏                                                                                                                             | 37/230 [01:11<05:20,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3038 [00:00<?, ?it/s]

 17%|████████████████████████▊                                                                                                                             | 38/230 [01:14<06:39,  2.08s/it]

Retrieving SummaryDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

 17%|█████████████████████████▍                                                                                                                            | 39/230 [01:15<05:57,  1.87s/it]

Retrieving SummaryDoc documents:   0%|          | 0/173 [00:00<?, ?it/s]

 17%|██████████████████████████                                                                                                                            | 40/230 [01:17<05:33,  1.76s/it]

Retrieving SummaryDoc documents:   0%|          | 0/90 [00:00<?, ?it/s]

 18%|██████████████████████████▋                                                                                                                           | 41/230 [01:18<05:19,  1.69s/it]

Retrieving SummaryDoc documents:   0%|          | 0/167 [00:00<?, ?it/s]

 18%|███████████████████████████▍                                                                                                                          | 42/230 [01:20<05:07,  1.64s/it]

Retrieving SummaryDoc documents:   0%|          | 0/320 [00:00<?, ?it/s]

 19%|████████████████████████████                                                                                                                          | 43/230 [01:22<05:02,  1.62s/it]

Retrieving SummaryDoc documents:   0%|          | 0/648 [00:00<?, ?it/s]

 19%|████████████████████████████▋                                                                                                                         | 44/230 [01:23<04:58,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/35 [00:00<?, ?it/s]

 20%|█████████████████████████████▎                                                                                                                        | 45/230 [01:25<04:44,  1.54s/it]

Retrieving SummaryDoc documents:   0%|          | 0/282 [00:00<?, ?it/s]

 20%|██████████████████████████████                                                                                                                        | 46/230 [01:26<04:48,  1.57s/it]

Retrieving SummaryDoc documents:   0%|          | 0/628 [00:00<?, ?it/s]

 20%|██████████████████████████████▋                                                                                                                       | 47/230 [01:28<04:47,  1.57s/it]

Retrieving SummaryDoc documents:   0%|          | 0/154 [00:00<?, ?it/s]

 21%|███████████████████████████████▎                                                                                                                      | 48/230 [01:30<05:16,  1.74s/it]

Retrieving SummaryDoc documents:   0%|          | 0/16 [00:00<?, ?it/s]

 21%|███████████████████████████████▉                                                                                                                      | 49/230 [01:31<05:00,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/8 [00:00<?, ?it/s]

 22%|████████████████████████████████▌                                                                                                                     | 50/230 [01:33<04:53,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/261 [00:00<?, ?it/s]

 22%|█████████████████████████████████▎                                                                                                                    | 51/230 [01:34<04:47,  1.61s/it]

Retrieving SummaryDoc documents:   0%|          | 0/190 [00:00<?, ?it/s]

 23%|█████████████████████████████████▉                                                                                                                    | 52/230 [01:36<04:42,  1.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/70 [00:00<?, ?it/s]

 23%|██████████████████████████████████▌                                                                                                                   | 53/230 [01:37<04:37,  1.57s/it]

Retrieving SummaryDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

 23%|███████████████████████████████████▏                                                                                                                  | 54/230 [01:39<04:34,  1.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/717 [00:00<?, ?it/s]

 24%|███████████████████████████████████▊                                                                                                                  | 55/230 [01:41<04:31,  1.55s/it]

Retrieving SummaryDoc documents:   0%|          | 0/99 [00:00<?, ?it/s]

 24%|████████████████████████████████████▌                                                                                                                 | 56/230 [01:42<04:22,  1.51s/it]

Retrieving SummaryDoc documents:   0%|          | 0/405 [00:00<?, ?it/s]

 25%|█████████████████████████████████████▏                                                                                                                | 57/230 [01:44<04:23,  1.52s/it]

Retrieving SummaryDoc documents:   0%|          | 0/457 [00:00<?, ?it/s]

 25%|█████████████████████████████████████▊                                                                                                                | 58/230 [01:45<04:30,  1.57s/it]

Retrieving SummaryDoc documents:   0%|          | 0/579 [00:00<?, ?it/s]

 26%|██████████████████████████████████████▍                                                                                                               | 59/230 [01:47<04:27,  1.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/656 [00:00<?, ?it/s]

 26%|███████████████████████████████████████▏                                                                                                              | 60/230 [01:48<04:23,  1.55s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1093 [00:00<?, ?it/s]

 27%|███████████████████████████████████████▊                                                                                                              | 61/230 [01:51<05:38,  2.00s/it]

Retrieving SummaryDoc documents:   0%|          | 0/6424 [00:00<?, ?it/s]

 27%|████████████████████████████████████████▍                                                                                                             | 62/230 [01:56<07:39,  2.73s/it]

Retrieving SummaryDoc documents:   0%|          | 0/2656 [00:00<?, ?it/s]

 27%|█████████████████████████████████████████                                                                                                             | 63/230 [01:59<07:51,  2.83s/it]

Retrieving SummaryDoc documents:   0%|          | 0/658 [00:00<?, ?it/s]

 28%|█████████████████████████████████████████▋                                                                                                            | 64/230 [02:00<06:39,  2.41s/it]

Retrieving SummaryDoc documents:   0%|          | 0/834 [00:00<?, ?it/s]

 28%|██████████████████████████████████████████▍                                                                                                           | 65/230 [02:02<05:50,  2.12s/it]

Retrieving SummaryDoc documents:   0%|          | 0/70 [00:00<?, ?it/s]

 29%|███████████████████████████████████████████                                                                                                           | 66/230 [02:03<05:22,  1.96s/it]

Retrieving SummaryDoc documents:   0%|          | 0/78 [00:00<?, ?it/s]

 29%|███████████████████████████████████████████▋                                                                                                          | 67/230 [02:05<04:58,  1.83s/it]

Retrieving SummaryDoc documents:   0%|          | 0/46 [00:00<?, ?it/s]

 30%|████████████████████████████████████████████▎                                                                                                         | 68/230 [02:06<04:42,  1.74s/it]

Retrieving SummaryDoc documents:   0%|          | 0/202 [00:00<?, ?it/s]

 30%|█████████████████████████████████████████████                                                                                                         | 69/230 [02:08<04:46,  1.78s/it]

Retrieving SummaryDoc documents:   0%|          | 0/365 [00:00<?, ?it/s]

 30%|█████████████████████████████████████████████▋                                                                                                        | 70/230 [02:10<04:33,  1.71s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1197 [00:00<?, ?it/s]

 31%|██████████████████████████████████████████████▎                                                                                                       | 71/230 [02:13<05:31,  2.09s/it]

Retrieving SummaryDoc documents:   0%|          | 0/316 [00:00<?, ?it/s]

 31%|██████████████████████████████████████████████▉                                                                                                       | 72/230 [02:14<04:57,  1.88s/it]

Retrieving SummaryDoc documents:   0%|          | 0/55 [00:00<?, ?it/s]

 32%|███████████████████████████████████████████████▌                                                                                                      | 73/230 [02:16<04:49,  1.84s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1090 [00:00<?, ?it/s]

 32%|████████████████████████████████████████████████▎                                                                                                     | 74/230 [02:19<05:38,  2.17s/it]

Retrieving SummaryDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

 33%|████████████████████████████████████████████████▉                                                                                                     | 75/230 [02:20<04:59,  1.93s/it]

Retrieving SummaryDoc documents:   0%|          | 0/56 [00:00<?, ?it/s]

 33%|█████████████████████████████████████████████████▌                                                                                                    | 76/230 [02:22<04:52,  1.90s/it]

Retrieving SummaryDoc documents:   0%|          | 0/7 [00:00<?, ?it/s]

 33%|██████████████████████████████████████████████████▏                                                                                                   | 77/230 [02:24<04:48,  1.89s/it]

Retrieving SummaryDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

 34%|██████████████████████████████████████████████████▊                                                                                                   | 78/230 [02:25<04:29,  1.78s/it]

Retrieving SummaryDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

 34%|███████████████████████████████████████████████████▌                                                                                                  | 79/230 [02:27<04:18,  1.71s/it]

Retrieving SummaryDoc documents:   0%|          | 0/21 [00:00<?, ?it/s]

 35%|████████████████████████████████████████████████████▏                                                                                                 | 80/230 [02:28<04:02,  1.62s/it]

Retrieving SummaryDoc documents:   0%|          | 0/82 [00:00<?, ?it/s]

 35%|████████████████████████████████████████████████████▊                                                                                                 | 81/230 [02:30<04:02,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/407 [00:00<?, ?it/s]

 36%|█████████████████████████████████████████████████████▍                                                                                                | 82/230 [02:32<03:58,  1.61s/it]

Retrieving SummaryDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

 36%|██████████████████████████████████████████████████████▏                                                                                               | 83/230 [02:33<03:52,  1.58s/it]

Retrieving SummaryDoc documents:   0%|          | 0/40 [00:00<?, ?it/s]

 37%|██████████████████████████████████████████████████████▊                                                                                               | 84/230 [02:35<03:43,  1.53s/it]

Retrieving SummaryDoc documents:   0%|          | 0/111 [00:00<?, ?it/s]

 37%|███████████████████████████████████████████████████████▍                                                                                              | 85/230 [02:36<03:47,  1.57s/it]

Retrieving SummaryDoc documents:   0%|          | 0/110 [00:00<?, ?it/s]

 37%|████████████████████████████████████████████████████████                                                                                              | 86/230 [02:38<03:58,  1.65s/it]

Retrieving SummaryDoc documents:   0%|          | 0/381 [00:00<?, ?it/s]

 38%|████████████████████████████████████████████████████████▋                                                                                             | 87/230 [02:40<03:52,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/337 [00:00<?, ?it/s]

 38%|█████████████████████████████████████████████████████████▍                                                                                            | 88/230 [02:42<04:12,  1.78s/it]

Retrieving SummaryDoc documents:   0%|          | 0/5 [00:00<?, ?it/s]

 39%|██████████████████████████████████████████████████████████                                                                                            | 89/230 [02:43<03:59,  1.70s/it]

Retrieving SummaryDoc documents:   0%|          | 0/13 [00:00<?, ?it/s]

 39%|██████████████████████████████████████████████████████████▋                                                                                           | 90/230 [02:45<03:46,  1.62s/it]

Retrieving SummaryDoc documents:   0%|          | 0/33 [00:00<?, ?it/s]

 40%|███████████████████████████████████████████████████████████▎                                                                                          | 91/230 [02:46<03:53,  1.68s/it]

Retrieving SummaryDoc documents:   0%|          | 0/152 [00:00<?, ?it/s]

 40%|████████████████████████████████████████████████████████████                                                                                          | 92/230 [02:48<04:04,  1.77s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

 40%|████████████████████████████████████████████████████████████▋                                                                                         | 93/230 [02:50<03:52,  1.70s/it]

Retrieving SummaryDoc documents:   0%|          | 0/5 [00:00<?, ?it/s]

 41%|█████████████████████████████████████████████████████████████▎                                                                                        | 94/230 [02:51<03:38,  1.61s/it]

Retrieving SummaryDoc documents:   0%|          | 0/62 [00:00<?, ?it/s]

 41%|█████████████████████████████████████████████████████████████▉                                                                                        | 95/230 [02:53<03:39,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/73 [00:00<?, ?it/s]

 42%|██████████████████████████████████████████████████████████████▌                                                                                       | 96/230 [02:54<03:29,  1.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/54 [00:00<?, ?it/s]

 42%|███████████████████████████████████████████████████████████████▎                                                                                      | 97/230 [02:56<03:30,  1.58s/it]

Retrieving SummaryDoc documents:   0%|          | 0/19 [00:00<?, ?it/s]

 43%|███████████████████████████████████████████████████████████████▉                                                                                      | 98/230 [02:58<03:28,  1.58s/it]

Retrieving SummaryDoc documents:   0%|          | 0/417 [00:00<?, ?it/s]

 43%|████████████████████████████████████████████████████████████████▌                                                                                     | 99/230 [02:59<03:26,  1.58s/it]

Retrieving SummaryDoc documents:   0%|          | 0/69 [00:00<?, ?it/s]

 43%|████████████████████████████████████████████████████████████████▊                                                                                    | 100/230 [03:01<03:18,  1.52s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

 44%|█████████████████████████████████████████████████████████████████▍                                                                                   | 101/230 [03:02<03:28,  1.62s/it]

Retrieving SummaryDoc documents:   0%|          | 0/49 [00:00<?, ?it/s]

 44%|██████████████████████████████████████████████████████████████████                                                                                   | 102/230 [03:04<03:39,  1.71s/it]

Retrieving SummaryDoc documents:   0%|          | 0/4 [00:00<?, ?it/s]

 45%|██████████████████████████████████████████████████████████████████▋                                                                                  | 103/230 [03:07<03:52,  1.83s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3 [00:00<?, ?it/s]

 45%|███████████████████████████████████████████████████████████████████▎                                                                                 | 104/230 [03:08<03:55,  1.87s/it]

Retrieving SummaryDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

 46%|████████████████████████████████████████████████████████████████████                                                                                 | 105/230 [03:10<03:39,  1.75s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3 [00:00<?, ?it/s]

 46%|████████████████████████████████████████████████████████████████████▋                                                                                | 106/230 [03:11<03:29,  1.69s/it]

Retrieving SummaryDoc documents:   0%|          | 0/366 [00:00<?, ?it/s]

 47%|█████████████████████████████████████████████████████████████████████▎                                                                               | 107/230 [03:13<03:23,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/44 [00:00<?, ?it/s]

 47%|█████████████████████████████████████████████████████████████████████▉                                                                               | 108/230 [03:15<03:14,  1.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/99 [00:00<?, ?it/s]

 47%|██████████████████████████████████████████████████████████████████████▌                                                                              | 109/230 [03:16<03:23,  1.69s/it]

Retrieving SummaryDoc documents:   0%|          | 0/29 [00:00<?, ?it/s]

 48%|███████████████████████████████████████████████████████████████████████▎                                                                             | 110/230 [03:18<03:36,  1.80s/it]

Retrieving SummaryDoc documents:   0%|          | 0/55 [00:00<?, ?it/s]

 48%|███████████████████████████████████████████████████████████████████████▉                                                                             | 111/230 [03:20<03:27,  1.74s/it]

Retrieving SummaryDoc documents:   0%|          | 0/11 [00:00<?, ?it/s]

 49%|████████████████████████████████████████████████████████████████████████▌                                                                            | 112/230 [03:22<03:17,  1.68s/it]

Retrieving SummaryDoc documents:   0%|          | 0/141 [00:00<?, ?it/s]

 49%|█████████████████████████████████████████████████████████████████████████▏                                                                           | 113/230 [03:23<03:11,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/69 [00:00<?, ?it/s]

 50%|█████████████████████████████████████████████████████████████████████████▊                                                                           | 114/230 [03:25<03:10,  1.64s/it]

Retrieving SummaryDoc documents:   0%|          | 0/403 [00:00<?, ?it/s]

 50%|██████████████████████████████████████████████████████████████████████████▌                                                                          | 115/230 [03:27<03:10,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/16 [00:00<?, ?it/s]

 50%|███████████████████████████████████████████████████████████████████████████▏                                                                         | 116/230 [03:28<03:16,  1.72s/it]

Retrieving SummaryDoc documents:   0%|          | 0/19 [00:00<?, ?it/s]

 51%|███████████████████████████████████████████████████████████████████████████▊                                                                         | 117/230 [03:30<03:08,  1.67s/it]

Retrieving SummaryDoc documents:   0%|          | 0/74 [00:00<?, ?it/s]

 51%|████████████████████████████████████████████████████████████████████████████▍                                                                        | 118/230 [03:32<03:10,  1.70s/it]

Retrieving SummaryDoc documents:   0%|          | 0/386 [00:00<?, ?it/s]

 52%|█████████████████████████████████████████████████████████████████████████████                                                                        | 119/230 [03:33<03:06,  1.68s/it]

Retrieving SummaryDoc documents:   0%|          | 0/18 [00:00<?, ?it/s]

 52%|█████████████████████████████████████████████████████████████████████████████▋                                                                       | 120/230 [03:35<02:58,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/281 [00:00<?, ?it/s]

 53%|██████████████████████████████████████████████████████████████████████████████▍                                                                      | 121/230 [03:36<02:55,  1.61s/it]

Retrieving SummaryDoc documents:   0%|          | 0/464 [00:00<?, ?it/s]

 53%|███████████████████████████████████████████████████████████████████████████████                                                                      | 122/230 [03:38<02:52,  1.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3521 [00:00<?, ?it/s]

 53%|███████████████████████████████████████████████████████████████████████████████▋                                                                     | 123/230 [03:41<03:39,  2.05s/it]

Retrieving SummaryDoc documents:   0%|          | 0/36 [00:00<?, ?it/s]

 54%|████████████████████████████████████████████████████████████████████████████████▎                                                                    | 124/230 [03:42<03:16,  1.85s/it]

Retrieving SummaryDoc documents:   0%|          | 0/68 [00:00<?, ?it/s]

 54%|████████████████████████████████████████████████████████████████████████████████▉                                                                    | 125/230 [03:44<03:01,  1.72s/it]

Retrieving SummaryDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

 55%|█████████████████████████████████████████████████████████████████████████████████▋                                                                   | 126/230 [03:46<02:57,  1.71s/it]

Retrieving SummaryDoc documents:   0%|          | 0/649 [00:00<?, ?it/s]

 55%|██████████████████████████████████████████████████████████████████████████████████▎                                                                  | 127/230 [03:48<03:12,  1.87s/it]

Retrieving SummaryDoc documents:   0%|          | 0/148 [00:00<?, ?it/s]

 56%|██████████████████████████████████████████████████████████████████████████████████▉                                                                  | 128/230 [03:50<03:06,  1.83s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1108 [00:00<?, ?it/s]

 56%|███████████████████████████████████████████████████████████████████████████████████▌                                                                 | 129/230 [03:53<03:53,  2.31s/it]

Retrieving SummaryDoc documents:   0%|          | 0/148 [00:00<?, ?it/s]

 57%|████████████████████████████████████████████████████████████████████████████████████▏                                                                | 130/230 [03:54<03:23,  2.04s/it]

Retrieving SummaryDoc documents:   0%|          | 0/92 [00:00<?, ?it/s]

 57%|████████████████████████████████████████████████████████████████████████████████████▊                                                                | 131/230 [03:57<03:24,  2.06s/it]

Retrieving SummaryDoc documents:   0%|          | 0/23 [00:00<?, ?it/s]

 57%|█████████████████████████████████████████████████████████████████████████████████████▌                                                               | 132/230 [03:58<03:11,  1.95s/it]

Retrieving SummaryDoc documents:   0%|          | 0/13 [00:00<?, ?it/s]

 58%|██████████████████████████████████████████████████████████████████████████████████████▏                                                              | 133/230 [04:00<03:06,  1.92s/it]

Retrieving SummaryDoc documents:   0%|          | 0/18 [00:00<?, ?it/s]

 58%|██████████████████████████████████████████████████████████████████████████████████████▊                                                              | 134/230 [04:02<02:53,  1.80s/it]

Retrieving SummaryDoc documents:   0%|          | 0/51 [00:00<?, ?it/s]

 59%|███████████████████████████████████████████████████████████████████████████████████████▍                                                             | 135/230 [04:03<02:43,  1.72s/it]

Retrieving SummaryDoc documents:   0%|          | 0/512 [00:00<?, ?it/s]

 59%|████████████████████████████████████████████████████████████████████████████████████████                                                             | 136/230 [04:05<02:33,  1.64s/it]

Retrieving SummaryDoc documents:   0%|          | 0/158 [00:00<?, ?it/s]

 60%|████████████████████████████████████████████████████████████████████████████████████████▊                                                            | 137/230 [04:06<02:31,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/32 [00:00<?, ?it/s]

 60%|█████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 138/230 [04:08<02:27,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3384 [00:00<?, ?it/s]

 60%|██████████████████████████████████████████████████████████████████████████████████████████                                                           | 139/230 [04:11<03:06,  2.04s/it]

Retrieving SummaryDoc documents:   0%|          | 0/751 [00:00<?, ?it/s]

 61%|██████████████████████████████████████████████████████████████████████████████████████████▋                                                          | 140/230 [04:12<02:49,  1.88s/it]

Retrieving SummaryDoc documents:   0%|          | 0/689 [00:00<?, ?it/s]

 61%|███████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 141/230 [04:14<02:36,  1.76s/it]

Retrieving SummaryDoc documents:   0%|          | 0/195 [00:00<?, ?it/s]

 62%|███████████████████████████████████████████████████████████████████████████████████████████▉                                                         | 142/230 [04:15<02:32,  1.73s/it]

Retrieving SummaryDoc documents:   0%|          | 0/319 [00:00<?, ?it/s]

 62%|████████████████████████████████████████████████████████████████████████████████████████████▋                                                        | 143/230 [04:17<02:24,  1.67s/it]

Retrieving SummaryDoc documents:   0%|          | 0/55 [00:00<?, ?it/s]

 63%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                                       | 144/230 [04:18<02:20,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/62 [00:00<?, ?it/s]

 63%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                                       | 145/230 [04:20<02:15,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/983 [00:00<?, ?it/s]

 63%|██████████████████████████████████████████████████████████████████████████████████████████████▌                                                      | 146/230 [04:22<02:15,  1.61s/it]

Retrieving SummaryDoc documents:   0%|          | 0/246 [00:00<?, ?it/s]

 64%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                                     | 147/230 [04:23<02:09,  1.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1300 [00:00<?, ?it/s]

 64%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                                     | 148/230 [04:26<02:39,  1.94s/it]

Retrieving SummaryDoc documents:   0%|          | 0/51 [00:00<?, ?it/s]

 65%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                    | 149/230 [04:27<02:23,  1.78s/it]

Retrieving SummaryDoc documents:   0%|          | 0/189 [00:00<?, ?it/s]

 65%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                   | 150/230 [04:29<02:18,  1.73s/it]

Retrieving SummaryDoc documents:   0%|          | 0/15 [00:00<?, ?it/s]

 66%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                                   | 151/230 [04:30<02:11,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/139 [00:00<?, ?it/s]

 66%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                                  | 152/230 [04:32<02:07,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/8 [00:00<?, ?it/s]

 67%|███████████████████████████████████████████████████████████████████████████████████████████████████                                                  | 153/230 [04:34<02:03,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/41 [00:00<?, ?it/s]

 67%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                                 | 154/230 [04:35<02:00,  1.58s/it]

Retrieving SummaryDoc documents:   0%|          | 0/237 [00:00<?, ?it/s]

 67%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                | 155/230 [04:37<01:56,  1.55s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1714 [00:00<?, ?it/s]

 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                                | 156/230 [04:40<02:45,  2.23s/it]

Retrieving SummaryDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

 68%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                                               | 157/230 [04:42<02:26,  2.00s/it]

Retrieving SummaryDoc documents:   0%|          | 0/94 [00:00<?, ?it/s]

 69%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                                              | 158/230 [04:43<02:14,  1.87s/it]

Retrieving SummaryDoc documents:   0%|          | 0/108 [00:00<?, ?it/s]

 69%|███████████████████████████████████████████████████████████████████████████████████████████████████████                                              | 159/230 [04:45<02:05,  1.76s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1373 [00:00<?, ?it/s]

 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 160/230 [04:48<02:31,  2.17s/it]

Retrieving SummaryDoc documents:   0%|          | 0/389 [00:00<?, ?it/s]

 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                            | 161/230 [04:50<02:16,  1.97s/it]

Retrieving SummaryDoc documents:   0%|          | 0/169 [00:00<?, ?it/s]

 70%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                            | 162/230 [04:51<02:05,  1.84s/it]

Retrieving SummaryDoc documents:   0%|          | 0/166 [00:00<?, ?it/s]

 71%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 163/230 [04:53<01:55,  1.73s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1460 [00:00<?, ?it/s]

 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                          | 164/230 [04:56<02:22,  2.16s/it]

Retrieving SummaryDoc documents:   0%|          | 0/138 [00:00<?, ?it/s]

 72%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                          | 165/230 [04:57<02:09,  1.99s/it]

Retrieving SummaryDoc documents:   0%|          | 0/2947 [00:00<?, ?it/s]

 72%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                         | 166/230 [05:01<02:32,  2.38s/it]

Retrieving SummaryDoc documents:   0%|          | 0/647 [00:00<?, ?it/s]

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                        | 167/230 [05:03<02:23,  2.28s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

 73%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 168/230 [05:04<02:13,  2.16s/it]

Retrieving SummaryDoc documents:   0%|          | 0/24 [00:00<?, ?it/s]

 73%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                       | 169/230 [05:06<02:06,  2.08s/it]

Retrieving SummaryDoc documents:   0%|          | 0/10 [00:00<?, ?it/s]

 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 170/230 [05:08<02:00,  2.01s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3 [00:00<?, ?it/s]

 74%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 171/230 [05:10<01:47,  1.82s/it]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

 75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 172/230 [05:11<01:43,  1.78s/it]

Retrieving SummaryDoc documents:   0%|          | 0/434 [00:00<?, ?it/s]

 75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                     | 173/230 [05:13<01:38,  1.72s/it]

Retrieving SummaryDoc documents:   0%|          | 0/270 [00:00<?, ?it/s]

 76%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 174/230 [05:15<01:41,  1.82s/it]

Retrieving SummaryDoc documents:   0%|          | 0/7 [00:00<?, ?it/s]

 76%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 175/230 [05:16<01:35,  1.74s/it]

Retrieving SummaryDoc documents:   0%|          | 0/569 [00:00<?, ?it/s]

 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                   | 176/230 [05:18<01:32,  1.71s/it]

Retrieving SummaryDoc documents:   0%|          | 0/5 [00:00<?, ?it/s]

 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 177/230 [05:20<01:26,  1.64s/it]

Retrieving SummaryDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

 77%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 178/230 [05:21<01:23,  1.61s/it]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

 78%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 179/230 [05:23<01:19,  1.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/49 [00:00<?, ?it/s]

 78%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 180/230 [05:24<01:19,  1.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/39 [00:00<?, ?it/s]

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 181/230 [05:26<01:20,  1.65s/it]

Retrieving SummaryDoc documents:   0%|          | 0/72 [00:00<?, ?it/s]

 79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 182/230 [05:28<01:26,  1.81s/it]

Retrieving SummaryDoc documents:   0%|          | 0/20 [00:00<?, ?it/s]

 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                              | 183/230 [05:30<01:21,  1.72s/it]

Retrieving SummaryDoc documents:   0%|          | 0/4 [00:00<?, ?it/s]

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 184/230 [05:32<01:20,  1.76s/it]

Retrieving SummaryDoc documents:   0%|          | 0/156 [00:00<?, ?it/s]

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                             | 185/230 [05:33<01:20,  1.79s/it]

Retrieving SummaryDoc documents:   0%|          | 0/925 [00:00<?, ?it/s]

 81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 186/230 [05:35<01:16,  1.74s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1762 [00:00<?, ?it/s]

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 187/230 [05:38<01:29,  2.07s/it]

Retrieving SummaryDoc documents:   0%|          | 0/45 [00:00<?, ?it/s]

 82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 188/230 [05:39<01:18,  1.87s/it]

Retrieving SummaryDoc documents:   0%|          | 0/986 [00:00<?, ?it/s]

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 189/230 [05:41<01:13,  1.78s/it]

Retrieving SummaryDoc documents:   0%|          | 0/69 [00:00<?, ?it/s]

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 190/230 [05:42<01:07,  1.68s/it]

Retrieving SummaryDoc documents:   0%|          | 0/781 [00:00<?, ?it/s]

 83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 191/230 [05:44<01:04,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/17 [00:00<?, ?it/s]

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 192/230 [05:45<01:00,  1.58s/it]

Retrieving SummaryDoc documents:   0%|          | 0/593 [00:00<?, ?it/s]

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 193/230 [05:48<01:06,  1.78s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3679 [00:00<?, ?it/s]

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 194/230 [05:51<01:20,  2.23s/it]

Retrieving SummaryDoc documents:   0%|          | 0/8 [00:00<?, ?it/s]

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 195/230 [05:52<01:08,  1.97s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3 [00:00<?, ?it/s]

 85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 196/230 [05:54<01:01,  1.81s/it]

Retrieving SummaryDoc documents:   0%|          | 0/44 [00:00<?, ?it/s]

 86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 197/230 [05:55<00:57,  1.73s/it]

Retrieving SummaryDoc documents:   0%|          | 0/436 [00:00<?, ?it/s]

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 198/230 [05:57<00:53,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/56 [00:00<?, ?it/s]

 87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 199/230 [05:58<00:50,  1.64s/it]

Retrieving SummaryDoc documents:   0%|          | 0/87 [00:00<?, ?it/s]

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 200/230 [06:00<00:48,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/188 [00:00<?, ?it/s]

 87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 201/230 [06:01<00:46,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/33 [00:00<?, ?it/s]

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 202/230 [06:03<00:44,  1.57s/it]

Retrieving SummaryDoc documents:   0%|          | 0/68 [00:00<?, ?it/s]

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 203/230 [06:05<00:42,  1.58s/it]

Retrieving SummaryDoc documents:   0%|          | 0/300 [00:00<?, ?it/s]

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 204/230 [06:06<00:40,  1.56s/it]

Retrieving SummaryDoc documents:   0%|          | 0/321 [00:00<?, ?it/s]

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 205/230 [06:08<00:39,  1.57s/it]

Retrieving SummaryDoc documents:   0%|          | 0/133 [00:00<?, ?it/s]

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 206/230 [06:09<00:36,  1.53s/it]

Retrieving SummaryDoc documents: 0it [00:00, ?it/s]

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 207/230 [06:10<00:34,  1.51s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3 [00:00<?, ?it/s]

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 208/230 [06:12<00:33,  1.54s/it]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 209/230 [06:14<00:34,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

 91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 210/230 [06:15<00:31,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 211/230 [06:17<00:30,  1.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/95 [00:00<?, ?it/s]

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 212/230 [06:19<00:27,  1.55s/it]

Retrieving SummaryDoc documents:   0%|          | 0/67 [00:00<?, ?it/s]

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 213/230 [06:20<00:28,  1.66s/it]

Retrieving SummaryDoc documents:   0%|          | 0/51 [00:00<?, ?it/s]

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 214/230 [06:22<00:26,  1.65s/it]

Retrieving SummaryDoc documents:   0%|          | 0/229 [00:00<?, ?it/s]

 93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 215/230 [06:24<00:23,  1.60s/it]

Retrieving SummaryDoc documents:   0%|          | 0/2757 [00:00<?, ?it/s]

 94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 216/230 [06:27<00:28,  2.04s/it]

Retrieving SummaryDoc documents:   0%|          | 0/219 [00:00<?, ?it/s]

 94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 217/230 [06:28<00:24,  1.85s/it]

Retrieving SummaryDoc documents:   0%|          | 0/100 [00:00<?, ?it/s]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 218/230 [06:29<00:20,  1.72s/it]

Retrieving SummaryDoc documents:   0%|          | 0/22 [00:00<?, ?it/s]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 219/230 [06:31<00:17,  1.63s/it]

Retrieving SummaryDoc documents:   0%|          | 0/214 [00:00<?, ?it/s]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 220/230 [06:32<00:16,  1.61s/it]

Retrieving SummaryDoc documents:   0%|          | 0/3070 [00:00<?, ?it/s]

 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 221/230 [06:35<00:17,  1.99s/it]

Retrieving SummaryDoc documents:   0%|          | 0/2 [00:00<?, ?it/s]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 222/230 [06:37<00:14,  1.81s/it]

Retrieving SummaryDoc documents:   0%|          | 0/282 [00:00<?, ?it/s]

 97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 223/230 [06:38<00:11,  1.70s/it]

Retrieving SummaryDoc documents:   0%|          | 0/52 [00:00<?, ?it/s]

 97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 224/230 [06:40<00:10,  1.69s/it]

Retrieving SummaryDoc documents:   0%|          | 0/9207 [00:00<?, ?it/s]

 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 225/230 [06:46<00:14,  2.99s/it]

Retrieving SummaryDoc documents:   0%|          | 0/55 [00:00<?, ?it/s]

 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 226/230 [06:47<00:10,  2.50s/it]

Retrieving SummaryDoc documents:   0%|          | 0/1385 [00:00<?, ?it/s]

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 227/230 [06:50<00:07,  2.59s/it]

Retrieving SummaryDoc documents:   0%|          | 0/8 [00:00<?, ?it/s]

 99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 228/230 [06:52<00:04,  2.34s/it]

Retrieving SummaryDoc documents:   0%|          | 0/295 [00:00<?, ?it/s]

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 229/230 [06:53<00:02,  2.12s/it]

Retrieving SummaryDoc documents:   0%|          | 0/336 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 230/230 [06:55<00:00,  1.81s/it]

In [91]:
len(sg_data)

215

In [59]:
sum(len(l) for l in sg_data.values())

113545

In [98]:
for k, v in sg_data.items():
    print(k, len(v), v[0]['formula_pretty'])

P1 14635 Ag13(PbO3)6
P-1 8518 Ag13(BiI4)14
P222 118 AlPS4
P222_1 28 Ag2Se
P2_12_12 144 Ag2S
P2_12_12_1 1036 Ag2GeO3
C222_1 240 Ag5(Sn3S8)2
C222 102 Al(SiO3)2
F222 35 AlCrGe
I222 41 AlPS4
I2_12_12_1 43 AlCuSeS
Pmm2 683 Ag3Sb
Pmc2_1 389 Ag2CO3
Pcc2 4 AlPO4
Pma2 23 BH8N
Pca2_1 383 AgAsO3
Pnc2 26 AgI3O8
Pmn2_1 616 Ag2SnHgS4
Pba2 29 Au2Se2O7
Pna2_1 1043 Ag2H12C6N3Cl
Pnn2 49 Ag2BiO3
Cmm2 124 Al3H36C12N3F4
Cmc2_1 745 Ag10Te4Br3
Ccc2 25 Al3Si3(PbO8)2
Amm2 3038 Ag5P(S2Cl)2
Aem2 35 AlPO4
Ama2 173 Ag2GePbS4
Aea2 90 AlH12(NF2)3
Fmm2 167 Ag3SBr
Fdd2 320 Ag2O3
Imm2 648 Ag2Bi2SeS3
Iba2 35 AlPO4
Ima2 282 Ag(OsO3)2
Pmmm 628 AgPdO2
Pnnn 154 BaCaDyBiO6
Pccm 16 AgAuS2
Pban 8 Ca(BO4)2
Pmma 261 Ag2Se
Pnna 190 Ag2BiO3
Pmna 70 AgAuO2
Pcca 45 AgAsS6N4(OF3)2
Pbam 717 AgGeO3
Pccn 99 As2O3
Pbcm 405 Ag3HSN3O2
Pnnm 457 Ag2WO4
Pmmn 579 Ag3Sb
Pbcn 656 Ag6Sn3(S5N)2
Pbca 1093 Ag2Hg(SeO3)2
Pnma 6424 Ag2(MoO4)3
Cmcm 2656 Ac2Mg
Cmce 658 Ag2PdCl4
Cmmm 834 AgBiO3
Cccm 70 AgO
Cmme 78 AgClO2
Ccce 46 Al2Fe(SiO5)2
Fmmm 202 AlCr2
Fddd 365 Ag2AsO2
Immm 1197 Ag2Au3N6Cl17
Ibam 316 Ag2O
Ibca 55 AlAs2
Imma 1090 Ag2Te2O7
P4 22 Ba14U2Fe4S25O
P4_1 56 B5H9
P4_2 7 Ca(BH4)2
P4_3 22 B5H9
I4 29 AlPbF5
I4_1 21 Ag3BiO3
P-4 82 Ag5CF4
I-4 407 Ag2HgI4
P4/m 39 Ba17SrSm12Cl68
P4_2/m 40 AsH12C4I3
P4/n 111 AgBF5
P4_2/n 110 AgSbO12
I4/m 381 AgClO3
I4_1/a 337 AgBrO4
P422 5 Ba3Sr9Al4(O4F)4
P42_12 13 BaSrEuWO6
P4_122 33 Ag3IrO4
P4_12_12 152 As2O5
P4_222 1 CsSbSI2
P4_22_12 5 Fe5Bi4O13F
P4_322 62 Ca2AsH4F13
P4_32_12 73 Ag2HgO2
I422 54 Ba(AlTe2)2
I4_122 19 AgAuO2
P4mm 417 Al2Cu2Ni
P4bm 69 Ba2MnSi2ClO7
P4_2cm 1 Mg6NiSn
P4_2nm 49 Ba4NaAl2B8(BrO6)3
P4cc 4 KAgSnSe3
P4nc 3 Ba5In4Bi5
P4_2mc 20 Ba(GeAs)2
P4_2bc 3 Cu(SbO2)2
I4mm 366 AlReGe
I4cm 44 Al3FeSi2
I4_1md 99 AgPb2Cl3OF
I4_1cd 29 B10H13
P-42m 55 Ag2HgI4
P-42c 11 Al5(BiS4)3
P-42_1m 141 Al(CN)3
P-42_1c 69 Ag2H12S(NO)4
P-4m2 403 AgI2
P-4c2 16 Co2Si3
P-4b2 19 Ba2CaI6
P-4n2 74 Ba2NaSr2(SbO4)3
I-4m2 386 Ag2BiSbSe4
I-4c2 18 BaSrV4(NiO4)4
I-42m 281 Ag2AsS4N
I-42d 464 Ac2S3
P4/mmm 3521 AgBiS2
P4/mcc 36 BaO10
P4/nbm 68 Ba(AlTe2)2
P4/nnc 20 Al2BiS4
P4/mbm 649 Ag2Hg5
P4/mnc 148 Al7CoCu2
P4/nmm 1108 AcBrO
P4/ncc 148 Al(BiO2)2
P4_2/mmc 92 AgO
P4_2/mcm 23 Bi2O3
P4_2/nbc 13 Cd3As2
P4_2/nnm 18 B
P4_2/mbc 51 AlH4NF4
P4_2/mnm 512 BN
P4_2/nmc 158 AsCF3
P4_2/ncm 32 AlH4NF4
I4/mmm 3384 Ac2Mg
I4/mcm 751 AcCuO2F
I4_1/amd 689 Ag6GeSO8
I4_1/acd 195 AgO2
P3 319 AlZn2Sb(HO)12
P3_1 55 BAsPbO5
P3_2 62 B(HO)3
R3 983 Ag3(AsO4)2
P-3 246 Ag25(BiO6)3
R-3 1300 Ag(Mo3S4)2
P312 51 Ba2Mg(FeO2)4
P321 189 Al17(BC3)6
P3_112 15 Ag2PHO4
P3_121 139 Ac
P3_212 8 AlGeMo
P3_221 41 AlPO4
R32 237 Ag3BO3
P3m1 1714 Ag11Hg9
P31m 45 Ag5(PbO3)2
P3c1 94 Ba2La3Ti3NbO15
P31c 108 Ag2CO3
R3m 1373 Ag2HgI4
R3c 389 Ag3AsO4
P-31m 169 Ag3O
P-31c 166 Ag5HgSbO6
P-3m1 1460 Ac2O3
P-3c1 138 Al(PO3)3
R-3m 2947 Ac
R-3c 647 Ac2S3
P6_1 24 Al2S3
P6_5 10 BaH2N2O5
P6_2 3 Ca(SO5)2
P6_4 2 Ca(SO5)2
P6_3 434 Al(BiCl)4
P-6 270 Ag2CO3
P6/m 7 ErNi3Ge2
P6_3/m 569 AcBr3
P622 5 Be6Al4Si12O37
P6_122 22 AgF3
P6_522 2 CaCO3
P6_222 49 BeF2
P6_422 39 Al2W
P6_322 72 Ag2SnO3
P6mm 20 AgI
P6cc 4 AlPO4
P6_3cm 156 Al3BC3
P6_3mc 925 AcN
P-6m2 1762 AcLa
P-6c2 45 BaHf(SiO3)3
P-62m 986 AcMg5
P-62c 69 Al2Ag2Bi2S3Cl8
P6/mmm 781 AcMg5
P6/mcc 17 Be3Al2(SiO3)6
P6_3/mcm 593 Al3(V3C2)4
P6_3/mmc 3679 Ac
P23 8 CeSe2
F23 3 Ca14Al12Zn4O35
I23 44 Al(Bi3O5)4
P2_13 436 Ag3SNO3
I2_13 56 Ag3AuSeS
Pm-3 87 Al17(Re2Si)2
Pn-3 188 Ag(W3Br7)2
Fm-3 33 B6H10N
Fd-3 68 Cd2BO4
Im-3 300 Al12Mo
Pa-3 321 Ag(BCl)6
Ia-3 133 AgSbF6
P4_232 3 AsH3
F432 2 LaCeBe26
F4_132 2 MgB12(H3O)12
I432 1 CeSe2
P4_332 95 BaSi2
P4_132 67 Ag3AuS2
I4_132 51 Ag3AuSe2
P-43m 229 AgB(CN)4
F-43m 2757 AcOF
I-43m 219 Ag3Ge5P6
P-43n 100 Ag3AsO4
F-43c 22 Co3B7IO13
I-43d 214 Ag15P4S16Cl3
Pm-3m 3070 Ac3Au
Pn-3n 2 Nd5Mo3O16
Pm-3n 282 Al3Ir
Pn-3m 52 Ag2O
Fm-3m 9207 Ac
Fm-3c 55 Ag13OsO6
Fd-3m 1385 Ag2MoO4
Fd-3c 8 CdCoH18N6Cl5
Im-3m 295 Ag
Ia-3d 336 Al2Cd3(GeO4)3

In [106]:
from pymatgen.io.ase import AseAtomsAdaptor as aaa

def get_composition(structure):
    atoms = Atoms(aaa.get_atoms(conventional_structure))
    composition = {}
    for a in atoms:
        if a.symbol not in composition:
            composition[a.symbol] = 1
        else:
            composition[a.symbol] += 1

    return composition

def get_cell_params(structure):
    atoms = Atoms(aaa.get_atoms(structure))
    return tuple(atoms.cell.cellpar().tolist())

In [125]:
# seen_mpids = set(base_df['mp_id'])
# with open('base_xrd_df.pkl', 'wb') as f:
#     pickle.dump(base_df, f)

In [126]:
from pymatgen.analysis.diffraction.xrd import XRDCalculator
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer


df_data = {
    'mp_id' : [],
    'formula': [],
    'composition': [],
    'crystal_system': [],
    'symmetry_symbol': [],
    'cell_params': [],
    'energy_above_hull': [],
    'xray_peaks': [],
    'xray_intensities': []
}
with MPRester(mute_progress_bars=True) as mpr:
    for i, (sg, doc_list) in enumerate(sg_data.items()):
        print(i, sg)
        
        for doc in tqdm(doc_list[:min(4096, len(doc_list))]):
            mpid = doc['material_id']
            if mpid in seen_mpids:
                continue
            
            structure = mpr.get_structure_by_material_id(mpid)
 
            sga = SpacegroupAnalyzer(structure)
            conventional_structure = sga.get_conventional_standard_structure()
            sga2 = SpacegroupAnalyzer(conventional_structure)

            
            conventional_sg = sga2.get_space_group_symbol()
            conventional_system = sga2.get_crystal_system()

            composition = str(get_composition(conventional_structure))
            cell_params = str(get_cell_params(conventional_structure))
            
            # this example shows how to obtain an XRD diffraction pattern
            # these patterns are calculated on-the-fly from the structure
            calculator = XRDCalculator(wavelength="CuKa")
            pattern = calculator.get_pattern(conventional_structure)
            peaks = '['+','.join([f'{s:.3f}' for s in pattern.x])+']'
            intensities = '['+','.join([f'{s:.3f}' for s in pattern.y])+']'

            df_data['mp_id'].append(mpid)
            df_data['formula'].append(doc['formula_pretty'])
            df_data['composition'].append(composition)
            df_data['crystal_system'].append(conventional_system)
            df_data['symmetry_symbol'].append(conventional_sg)
            df_data['cell_params'].append(cell_params)
            df_data['energy_above_hull'].append(doc['energy_above_hull'])
            df_data['xray_peaks'].append(peaks)
            df_data['xray_intensities'].append(intensities)

0 P1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4096/4096 [00:00<00:00, 348158.26it/s]

1 P-1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4096/4096 [00:00<00:00, 340877.18it/s]

2 P222

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 118/118 [00:00<00:00, 283301.59it/s]

3 P222_1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:00<00:00, 165642.47it/s]

4 P2_12_12

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 144/144 [00:00<00:00, 261236.93it/s]

5 P2_12_12_1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1036/1036 [00:00<00:00, 102302.51it/s]

6 C222_1

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 240/240 [00:00<00:00, 59588.76it/s]

7 C222

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 102/102 [00:00<00:00, 58879.58it/s]

8 F222

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 30305.66it/s]

9 I222

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41/41 [00:00<00:00, 51104.45it/s]

10 I2_12_12_1

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 65871.10it/s]

11 Pmm2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 683/683 [00:00<00:00, 112792.73it/s]

12 Pmc2_1

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 124949.02it/s]

13 Pcc2

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 19645.45it/s]

14 Pma2

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 66392.97it/s]

15 Pca2_1

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 383/383 [00:00<00:00, 128482.64it/s]

16 Pnc2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 109161.07it/s]

17 Pmn2_1

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 616/616 [00:00<00:00, 216443.94it/s]

18 Pba2

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [00:00<00:00, 23481.62it/s]

19 Pna2_1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1043/1043 [00:00<00:00, 149341.45it/s]

20 Pnn2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:00<00:00, 118935.70it/s]

21 Cmm2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 124/124 [00:00<00:00, 173828.11it/s]

22 Cmc2_1

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 745/745 [00:00<00:00, 65001.59it/s]

23 Ccc2

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:00<00:00, 38130.04it/s]

24 Amm2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3038/3038 [00:00<00:00, 208037.48it/s]

25 Aem2

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 91407.62it/s]

26 Ama2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 173/173 [00:00<00:00, 131024.66it/s]

27 Aea2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90/90 [00:00<00:00, 129676.18it/s]

28 Fmm2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 167/167 [00:00<00:00, 157616.73it/s]

29 Fdd2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 320/320 [00:00<00:00, 125331.71it/s]

30 Imm2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 648/648 [00:00<00:00, 142187.23it/s]

31 Iba2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 121122.64it/s]

32 Ima2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 282/282 [00:00<00:00, 210386.65it/s]

33 Pmmm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 628/628 [00:00<00:00, 230549.05it/s]

34 Pnnn

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 154/154 [00:00<00:00, 212614.49it/s]

35 Pccm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 93596.74it/s]

36 Pban

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 70197.56it/s]

37 Pmma

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 261/261 [00:00<00:00, 267459.89it/s]

38 Pnna

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 190/190 [00:00<00:00, 296582.72it/s]

39 Pmna

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 70/70 [00:00<00:00, 221585.87it/s]

40 Pcca

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [00:00<00:00, 176891.92it/s]

41 Pbam

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 717/717 [00:00<00:00, 326917.70it/s]

42 Pccn

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:00<00:00, 153110.65it/s]

43 Pbcm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 405/405 [00:00<00:00, 122844.45it/s]

44 Pnnm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 457/457 [00:00<00:00, 196232.28it/s]

45 Pmmn

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 579/579 [00:00<00:00, 263537.93it/s]

46 Pbcn

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 656/656 [00:00<00:00, 299723.68it/s]

47 Pbca

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1093/1093 [00:00<00:00, 309587.67it/s]

48 Pnma

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4096/4096 [00:00<00:00, 336556.62it/s]

49 Cmcm

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2656/2656 [00:00<00:00, 317245.38it/s]

50 Cmce

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 658/658 [00:00<00:00, 324994.35it/s]

51 Cmmm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 834/834 [00:00<00:00, 284255.61it/s]

52 Cccm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 70/70 [00:00<00:00, 83862.12it/s]

53 Cmme

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 78/78 [00:00<00:00, 96591.59it/s]

54 Ccce

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 46/46 [00:00<00:00, 137616.25it/s]

55 Fmmm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 202/202 [00:00<00:00, 195624.43it/s]

56 Fddd

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 365/365 [00:00<00:00, 229420.19it/s]

57 Immm

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1197/1197 [00:00<00:00, 268897.32it/s]

58 Ibam

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 316/316 [00:00<00:00, 83316.57it/s]

59 Ibca

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 55/55 [00:00<00:00, 118544.05it/s]

60 Imma

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1090/1090 [00:00<00:00, 161701.67it/s]

61 P4

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 93395.43it/s]

62 P4_1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 56/56 [00:00<00:00, 139395.27it/s]

63 P4_2

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 49594.81it/s]

64 P4_3

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 129236.26it/s]

65 I4

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [00:00<00:00, 144631.17it/s]

66 I4_1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 128961.03it/s]

67 P-4

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 82/82 [00:00<00:00, 188870.36it/s]

68 I-4

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 407/407 [00:00<00:00, 118399.34it/s]

69 P4/m

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [00:00<00:00, 56328.46it/s]

70 P4_2/m

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 91478.82it/s]

71 P4/n

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 122517.83it/s]

72 P4_2/n

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 110/110 [00:00<00:00, 204600.20it/s]

73 I4/m

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 381/381 [00:00<00:00, 253133.19it/s]

74 I4_1/a

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 337/337 [00:00<00:00, 288760.05it/s]

75 P422

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 33447.40it/s]

76 P42_12

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 71744.67it/s]

77 P4_122

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:00<00:00, 110996.02it/s]

78 P4_12_12

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 152/152 [00:00<00:00, 167200.16it/s]

79 P4_222

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 9320.68it/s]

80 P4_22_12

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 40175.33it/s]

81 P4_322

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62/62 [00:00<00:00, 153782.88it/s]

82 P4_32_12

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 240332.96it/s]

83 I422

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 54/54 [00:00<00:00, 142897.42it/s]

84 I4_122

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 105412.40it/s]

85 P4mm

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 417/417 [00:00<00:00, 63733.00it/s]

86 P4bm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 69/69 [00:00<00:00, 62024.64it/s]

87 P4_2cm

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 6374.32it/s]

88 P4_2nm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:00<00:00, 92702.25it/s]

89 P4cc

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 21902.37it/s]

90 P4nc

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 16935.28it/s]

91 P4_2mc

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 75777.85it/s]

92 P4_2bc

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 16688.21it/s]

93 I4mm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 366/366 [00:00<00:00, 178190.98it/s]

94 I4cm

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 122380.22it/s]

95 I4_1md

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99/99 [00:00<00:00, 154765.60it/s]

96 I4_1cd

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [00:00<00:00, 153579.31it/s]

97 P-42m

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 55/55 [00:00<00:00, 206523.47it/s]

98 P-42c

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 65073.83it/s]

99 P-42_1m

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 141/141 [00:00<00:00, 200134.30it/s]

100 P-42_1c

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 69/69 [00:00<00:00, 217926.94it/s]

101 P-4m2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 403/403 [00:00<00:00, 301947.93it/s]

102 P-4c2

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 97400.38it/s]

103 P-4b2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 116679.03it/s]

104 P-4n2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 74/74 [00:00<00:00, 239120.57it/s]

105 I-4m2

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 386/386 [00:00<00:00, 292080.34it/s]

106 I-4c2

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 67710.74it/s]

107 I-42m

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 281/281 [00:00<00:00, 67930.80it/s]

108 I-42d

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 464/464 [00:00<00:00, 53679.69it/s]

109 P4/mmm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3521/3521 [00:00<00:00, 94248.31it/s]

110 P4/mcc

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36/36 [00:00<00:00, 124378.04it/s]

111 P4/nbm

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 68/68 [00:00<00:00, 152683.44it/s]

112 P4/nnc

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 62508.26it/s]

113 P4/mbm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 649/649 [00:00<00:00, 169232.41it/s]

114 P4/mnc

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 148/148 [00:00<00:00, 155656.22it/s]

115 P4/nmm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1108/1108 [00:00<00:00, 74661.24it/s]

116 P4/ncc

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 148/148 [00:00<00:00, 83954.15it/s]

117 P4_2/mmc

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 92/92 [00:00<00:00, 101439.53it/s]

118 P4_2/mcm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 74782.16it/s]

119 P4_2/nbc

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 60584.39it/s]

120 P4_2/nnm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 73944.63it/s]

121 P4_2/mbc

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:00<00:00, 117597.31it/s]

122 P4_2/mnm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:00<00:00, 166846.68it/s]

123 P4_2/nmc

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 158/158 [00:00<00:00, 150306.20it/s]

124 P4_2/ncm

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:00<00:00, 32864.28it/s]

125 I4/mmm

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3384/3384 [00:00<00:00, 109425.06it/s]

126 I4/mcm

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 751/751 [00:00<00:00, 96242.55it/s]

127 I4_1/amd

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 689/689 [00:00<00:00, 99475.94it/s]

128 I4_1/acd

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 195/195 [00:00<00:00, 195526.96it/s]

129 P3

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 319/319 [00:00<00:00, 114396.63it/s]

130 P3_1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 55/55 [00:00<00:00, 156186.00it/s]

131 P3_2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 62/62 [00:00<00:00, 177870.62it/s]

132 R3

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 983/983 [00:00<00:00, 246827.16it/s]

133 P-3

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 246/246 [00:00<00:00, 280456.32it/s]

134 R-3

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1300/1300 [00:00<00:00, 324404.76it/s]

135 P312

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:00<00:00, 241160.66it/s]

136 P321

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 189/189 [00:00<00:00, 306070.83it/s]

137 P3_112

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 113359.57it/s]

138 P3_121

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 139/139 [00:00<00:00, 284533.07it/s]

139 P3_212

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 102612.94it/s]

140 P3_221

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41/41 [00:00<00:00, 118190.01it/s]

141 R32

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 237/237 [00:00<00:00, 141421.26it/s]

142 P3m1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1714/1714 [00:00<00:00, 300519.90it/s]

143 P31m

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [00:00<00:00, 61984.79it/s]

144 P3c1

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 94/94 [00:00<00:00, 84064.94it/s]

145 P31c

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 108/108 [00:00<00:00, 92578.14it/s]

146 R3m

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1373/1373 [00:00<00:00, 273135.05it/s]

147 R3c

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 273709.82it/s]

148 P-31m

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 169/169 [00:00<00:00, 202293.77it/s]

149 P-31c

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 166/166 [00:00<00:00, 232627.62it/s]

150 P-3m1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1460/1460 [00:00<00:00, 290029.55it/s]

151 P-3c1

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 138/138 [00:00<00:00, 255547.00it/s]

152 R-3m

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2947/2947 [00:00<00:00, 317655.58it/s]

153 R-3c

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 647/647 [00:00<00:00, 296937.81it/s]

154 P6_1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 144631.17it/s]

155 P6_5

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 96420.78it/s]

156 P6_2

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 35848.75it/s]

157 P6_4

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 27503.63it/s]

158 P6_3

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 434/434 [00:00<00:00, 314826.69it/s]

159 P-6

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 270/270 [00:00<00:00, 169988.30it/s]

160 P6/m

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 64527.75it/s]

161 P6_3/m

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 569/569 [00:00<00:00, 319058.69it/s]

162 P622

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 11178.85it/s]

163 P6_122

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 35517.59it/s]

164 P6_522

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 12318.07it/s]

165 P6_222

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [00:00<00:00, 131575.48it/s]

166 P6_422

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [00:00<00:00, 136088.07it/s]

167 P6_322

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 72/72 [00:00<00:00, 210006.88it/s]

168 P6mm

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 121927.44it/s]

169 P6cc

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 37200.04it/s]

170 P6_3cm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 156/156 [00:00<00:00, 169247.65it/s]

171 P6_3mc

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 925/925 [00:00<00:00, 295576.05it/s]

172 P-6m2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1762/1762 [00:00<00:00, 283949.88it/s]

173 P-6c2

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 45/45 [00:00<00:00, 162850.46it/s]

174 P-62m

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 986/986 [00:00<00:00, 318195.26it/s]

175 P-62c

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 69/69 [00:00<00:00, 101403.99it/s]

176 P6/mmm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 781/781 [00:00<00:00, 129108.92it/s]

177 P6/mcc

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 76670.07it/s]

178 P6_3/mcm

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 593/593 [00:00<00:00, 191192.43it/s]

179 P6_3/mmc

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3679/3679 [00:00<00:00, 137208.19it/s]

180 P23

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 47594.94it/s]

181 F23

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 11356.42it/s]

182 I23

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 44/44 [00:00<00:00, 161601.91it/s]

183 P2_13

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 436/436 [00:00<00:00, 270120.61it/s]

184 I2_13

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 56/56 [00:00<00:00, 190495.56it/s]

185 Pm-3

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 87/87 [00:00<00:00, 133566.78it/s]

186 Pn-3

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 188/188 [00:00<00:00, 117849.22it/s]

187 Fm-3

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:00<00:00, 73117.82it/s]

188 Fd-3

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 68/68 [00:00<00:00, 64483.99it/s]

189 Im-3

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:00<00:00, 92115.02it/s]

190 Pa-3

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321/321 [00:00<00:00, 169932.04it/s]

191 Ia-3

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133/133 [00:00<00:00, 170385.59it/s]

192 P4_232

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3979.42it/s]

193 F432

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 6186.29it/s]

194 F4_132

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 14614.30it/s]

195 I432

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 6034.97it/s]

196 P4_332

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 95/95 [00:00<00:00, 53212.99it/s]

197 P4_132

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [00:00<00:00, 150680.09it/s]

198 I4_132

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:00<00:00, 147320.60it/s]

199 P-43m

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 229/229 [00:00<00:00, 214587.94it/s]

200 F-43m

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2757/2757 [00:00<00:00, 103726.09it/s]

201 I-43m

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 219/219 [00:00<00:00, 64564.04it/s]

202 P-43n

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 48742.64it/s]

203 F-43c

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 26584.47it/s]

204 I-43d

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 214/214 [00:00<00:00, 96795.11it/s]

205 Pm-3m

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3070/3070 [00:00<00:00, 113139.44it/s]

206 Pn-3n

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 9269.18it/s]

207 Pm-3n

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 282/282 [00:00<00:00, 130034.49it/s]

208 Pn-3m

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52/52 [00:00<00:00, 93326.40it/s]

209 Fm-3m

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4096/4096 [35:40<00:00,  1.91it/s]

210 Fm-3c

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 55/55 [01:06<00:00,  1.21s/it]

211 Fd-3m

 43%|███████████████████████████████████████████████████████████████▉                                                                                    | 598/1385 [08:04<06:59,  1.87it/s]spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
spglib: ssm_get_exact_positions failed.
spglib: get_bravais_exact_positions_and_lattice failed.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1385/1385 [18:05<00:00,  1.28it/s]

212 Fd-3c

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [01:01<00:00,  7.65s/it]

213 Im-3m

 32%|███████████████████████████████████████████████▊                                                                                                      | 94/295 [00:47<01:20,  2.48it/s]/media/colin/Shared/colin/git/materials-ml-workshop/env/lib/python3.10/site-packages/pymatgen/core/composition.py:328: UserWarning: No Pauling electronegativity for He. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  return sum((el.X * abs(amt) for el, amt in self.items())) / self.num_atoms
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 295/295 [02:37<00:00,  1.88it/s]

214 Ia-3d

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 336/336 [06:28<00:00,  1.16s/it]

In [130]:
# print(df_data.keys())


# test_df = pd.DataFrame(df_data)
# test_df.to_csv('xrd_dataset_v3.csv')

dict_keys(['mp_id', 'formula', 'composition', 'crystal_system', 'symmetry_symbol', 'cell_params', 'energy_above_hull', 'xray_peaks', 'xray_intensities'])

In [149]:
base_df.drop(columns='Unnamed: 0')

,Unnamed: 0,mp_id,formula,composition,crystal_system,symmetry_symbol,cell_params,energy_above_hull,xray_peaks,xray_intensities
0,0,mp-676840,Ag13(PbO3)6,"{'Ag': 26, 'Pb': 12, 'O': 36}",triclinic,P1,"(6.002268, 10.397799745616618, 19.466327337319...",0.007080,"[4.539,8.504,9.086,9.625,9.662,12.428,12.486,1...","[2.848,0.094,6.001,3.006,2.908,4.037,4.086,46...."
1,1,mp-685283,Ag13Bi15I64,"{'Ag': 13, 'Bi': 15, 'I': 64}",triclinic,P1,"(8.894472385608267, 9.034189542918936, 59.5692...",0.083551,"[1.485,2.970,4.455,5.941,7.429,8.917,10.407,11...","[100.000,0.282,0.843,0.044,0.360,0.059,2.260,0..."
2,2,mp-1229151,Ag15S5I4Br,"{'Ag': 15, 'S': 5, 'I': 4, 'Br': 1}",triclinic,P1,"(6.993913570662637, 8.558995140558554, 10.9872...",0.065281,"[8.805,10.757,11.873,13.371,13.441,15.703,16.3...","[0.410,0.293,0.217,0.223,0.179,0.159,0.162,0.1..."
3,3,mp-759792,Ag2B8O13,"{'Ag': 8, 'B': 32, 'O': 52}",triclinic,P1,"(7.898226, 10.663953129513134, 12.038956354262...",0.011548,"[7.451,8.414,10.253,11.203,12.162,13.467,13.46...","[2.472,0.055,0.002,0.459,0.076,33.647,27.434,8..."
4,4,mp-686742,Ag2H21N7(ClO4)2,"{'Ag': 2, 'H': 21, 'N': 7, 'Cl': 2, 'O': 8}",triclinic,P1,"(8.185132, 8.714175033958062, 9.08744340539081...",0.700030,"[10.854,10.961,11.426,11.674,14.809,15.183,15....","[8.524,100.000,65.581,91.596,2.314,4.840,1.231..."
...,...,...,...,...,...,...,...,...,...,...
85865,85865,mp-867239,Ce2AgPb,"{'Ce': 8, 'Ag': 4, 'Pb': 4}",cubic,Fm-3m,"(7.708982, 7.708982, 7.708982, 90.0, 90.0, 90.0)",0.083034,"[19.949,23.075,32.861,38.741,40.537,47.158,51....","[4.983,0.450,100.000,3.153,0.169,18.241,1.500,..."
85866,85866,mp-1183725,Ce2AgSn,"{'Ce': 8, 'Ag': 4, 'Sn': 4}",cubic,Fm-3m,"(7.62461, 7.62461, 7.62461, 90.0, 90.0, 90.0)",0.086914,"[20.172,23.333,33.235,39.187,41.006,47.712,52....","[0.043,0.949,100.000,0.049,0.274,18.078,0.039,..."
85867,85867,mp-985438,Ce2CdHg,"{'Ce': 8, 'Cd': 4, 'Hg': 4}",cubic,Fm-3m,"(7.701154, 7.701154, 7.701154, 90.0, 90.0, 90.0)",0.045387,"[19.969,23.098,32.895,38.782,40.580,47.209,51....","[4.338,0.407,100.000,2.732,0.153,18.228,1.283,..."
85868,85868,mp-1183867,Ce2CdIn,"{'Ce': 8, 'Cd': 4, 'In': 4}",cubic,Fm-3m,"(7.681074, 7.681074, 7.681074, 90.0, 90.0, 90.0)",0.043177,"[20.022,23.160,32.984,38.887,40.691,47.340,51....","[0.003,1.003,100.000,0.002,0.320,17.959,0.001,..."
85869,85869,mp-1183762,Ce2CdPb,"{'Ce': 8, 'Cd': 4, 'Pb': 4}",cubic,Fm-3m,"(7.7971400000000015, 7.7971400000000015, 7.797...",0.065631,"[19.721,22.810,32.479,38.285,40.059,46.593,51....","[4.684,0.496,100.000,2.969,0.189,18.348,1.408,..."

In [150]:
full_df = pd.concat([base_df.drop(columns='Unnamed: 0'), pd.DataFrame(df_data)])
print(len(set(full_df['mp_id'])))

91145

,mp_id,formula,composition,crystal_system,symmetry_symbol,cell_params,energy_above_hull,xray_peaks,xray_intensities
9000,mp-779084,LiCr(PO3)3,"{'Li': 4, 'Cr': 4, 'P': 12, 'O': 36}",orthorhombic,P2_12_12_1,"(5.532192000000001, 10.725322000000002, 11.669...",0.075756,"[11.205,15.185,16.531,17.302,17.743,18.042,18....","[8.252,40.205,21.474,83.744,77.603,31.870,30.8..."
9001,mp-780193,LiCr(PO3)3,"{'Li': 4, 'Cr': 4, 'P': 12, 'O': 36}",orthorhombic,P2_12_12_1,"(8.41278, 8.755500999999999, 9.066855999999998...",0.023640,"[14.061,14.362,14.602,17.590,19.582,20.285,21....","[0.250,0.660,0.002,3.985,26.291,8.394,7.511,1...."
9002,mp-780490,LiCr(PO4)2,"{'Li': 4, 'Cr': 4, 'P': 8, 'O': 32}",orthorhombic,P2_12_12_1,"(5.182686, 10.526597000000002, 11.085474, 90.0...",0.093594,"[11.593,15.990,16.845,18.088,18.662,18.902,19....","[26.250,0.023,5.586,1.374,68.961,0.501,1.710,0..."
9003,mp-1223201,LiCr4(PO4)3,"{'Li': 4, 'Cr': 16, 'P': 12, 'O': 48}",orthorhombic,P2_12_12_1,"(6.31577604, 10.543954670000002, 14.5099841900...",0.012109,"[10.371,12.200,14.822,15.300,16.360,16.817,17....","[0.448,4.411,32.458,16.242,4.516,4.334,13.246,..."
9004,mp-12185,LiCu(PO3)3,"{'Li': 4, 'Cu': 4, 'P': 12, 'O': 36}",orthorhombic,P2_12_12_1,"(8.165365519999998, 8.553718909999999, 8.67629...",0.000000,"[14.542,14.899,15.000,18.170,20.472,20.769,21....","[22.238,5.545,0.311,100.000,13.369,4.745,25.88..."
...,...,...,...,...,...,...,...,...,...
5270,mp-1364038,Zn3Si3(SnO6)2,"{'Zn': 24, 'Si': 24, 'Sn': 16, 'O': 96}",cubic,Ia-3d,"(12.35908, 12.35908, 12.35908, 90.0, 90.0, 90.0)",0.308748,"[17.577,20.324,26.994,28.897,32.396,34.024,35....","[5.740,45.839,4.501,67.368,55.614,0.429,100.00..."
5271,mp-1163950,Zn3Si3(WO6)2,"{'Zn': 24, 'Si': 24, 'W': 16, 'O': 96}",cubic,Ia-3d,"(12.137336, 12.137336, 12.137336, 90.0, 90.0, ...",0.226553,"[17.901,20.699,27.497,29.436,33.005,34.665,36....","[3.294,74.831,2.346,56.137,25.406,0.374,100.00..."
5272,mp-1327509,Zn3Sn2(GeO4)3,"{'Zn': 24, 'Sn': 16, 'Ge': 24, 'O': 96}",cubic,Ia-3d,"(12.573034, 12.573034, 12.573034, 90.0, 90.0, ...",0.227320,"[17.276,19.974,26.526,28.395,31.830,33.428,34....","[0.201,16.587,0.840,64.249,87.208,4.704,100.00..."
5273,mp-648774,Zr2Cl5,"{'Zr': 96, 'Cl': 240}",cubic,Ia-3d,"(21.790819064017104, 21.790819064017104, 21.79...",0.059570,"[9.943,11.486,15.213,16.271,18.207,19.104,19.9...","[0.626,100.000,6.746,1.780,0.009,2.667,4.761,0..."
5274,mp-531184,Zr6NCl15,"{'Zr': 96, 'N': 16, 'Cl': 240}",cubic,Ia-3d,"(21.44328662, 21.44328662, 21.44328662, 90.0, ...",0.000000,"[10.104,11.673,15.462,16.536,18.504,19.416,20....","[0.389,100.000,5.158,0.569,0.025,1.852,1.828,0..."

In [157]:
import ast
import numpy as np

for i, row in full_df.iterrows():
    x = np.array(ast.literal_eval(row['xray_intensities']))
    if not np.isfinite(x).all():
        print(i)

In [162]:
full_df.to_csv('xrd_dataset_full.csv', index=False)